【WIP】ユーザーマイページの作成（マークアップ）
mk299/fleamarket_sample_kagawa-d pull request #12
Opened 2021-01-31 03:15 UTC by mk299

# What

# Why

2021-02-03 05:42 UTC, obami1105 commented
LGTMです◎

2021-02-03 06:35 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。

コメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-02-03 06:35 UTC, yupimaru commented on app/views/credit_cards/new.html.haml
> +                = f.select :exp_month, [['01',1],['02',2],['03',3],['04',4],['05',5],['06',6],['07',7],['08',8],['09',9],['10',10],['11',11],['12',12]],{include_blank: '---'}, class: 'Exp__field--sel
```haml
= f.select :exp_month, [['01',1],['02',2],['03',3],['04',4],['05',5],['06',6],['07',7],['08',8],['09',9],['10',10],['11',11],['12',12]],{include_blank: '---'}, class: 'Exp__field--select', name: 'exp_month', id:'exp_month'
```

上記コードですが、もう少しシンプルに書けそうです。
第二引数の書き方を工夫してみましょう。

2021-02-03 06:35 UTC, yupimaru commented on app/views/credit_cards/new.html.haml
> +                = f.select :exp_year, [['21',2021],['22',2022],['23',2023],['24',2024],['25',2025],['26',2026],['27',2027],['28',2028],['29',2029],['30',2030]], {include_blank: '---'}, class: 'Exp__f
```haml
= f.select :exp_year, [['21',2021],['22',2022],['23',2023],['24',2024],['25',2025],['26',2026],['27',2027],['28',2028],['29',2029],['30',2030]], {include_blank: '---'}, class: 'Exp__field--select', name: 'exp_year', id:'exp_year'
```

上記コードですが、もう少しシンプルに書けそうです。
第二引数の書き方を工夫してみましょう。
また、上記記述ですと、2030年以降の有効期限のクレジットカードが出てきたときに登録できなくなります。
ここも工夫してみましょう。

2021-02-03 06:35 UTC, yupimaru commented on app/views/users/_mypage_side.html.haml
> +.SideNav
```haml
%li.NavLists__item
  = link_to '' do
    = hogehoge
    = icon('fas', 'chevron-right', class: "Nav__icon")
```

上記の形が繰り返し使用されているようです。
部分テンプレート化出来ないか工夫してみましょう。

2021-02-03 06:35 UTC, yupimaru commented on app/controllers/users_controller.rb
> +  # before_action :authenticate_user!
```haml
# before_action :authenticate_user!
```

上記コメントアウトは必要なものですか？
もし、必要なのであればなぜコメントアウトとして残しているのか簡単に記述しておきましょう。
不要な記述であれば削除しましょう。

2021-02-06 02:06 UTC, mk299 commented on app/views/credit_cards/new.html.haml
> +                = f.select :exp_month, [['01',1],['02',2],['03',3],['04',4],['05',5],['06',6],['07',7],['08',8],['09',9],['10',10],['11',11],['12',12]],{include_blank: '---'}, class: 'Exp__field--sel
年と月をdate_selectタグに変更しました。

2021-02-06 02:07 UTC, mk299 commented on app/views/credit_cards/new.html.haml
> +                = f.select :exp_year, [['21',2021],['22',2022],['23',2023],['24',2024],['25',2025],['26',2026],['27',2027],['28',2028],['29',2029],['30',2030]], {include_blank: '---'}, class: 'Exp__f
今年から10年後まで選択できるように変更しました。

2021-02-06 02:07 UTC, mk299 commented on app/views/users/_mypage_side.html.haml
> +.SideNav
リンクリストを部分テンプレートに変更しました。

2021-02-06 02:07 UTC, mk299 commented on app/controllers/users_controller.rb
> +  # before_action :authenticate_user!
不要コードを削除しました。

2021-02-06 02:10 UTC, yupimaru commented
レビュー依頼ありがとうございます。

こちらのプルリクエストにて、コンフリクトが起きていますので、まずはこちらを解消してください！
githubのブラウザエディタでコンフリクトを解消できますので、「Resolve conflicts」をクリックしましょう。

2021-02-06 02:22 UTC, mk299 commented
コンフリクト解消しました！

2021-02-06 02:29 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正をもって**LGTM**とさせていただきます。
マイページのマークアップお疲れ様でした。
masterブランチへマージ後、次の実装へ進みましょう。

引き続き実装頑張っていきましょう。応援しております！

2021-02-06 02:30 UTC, merged