【WIP】商品購入機能の追加
mk299/fleamarket_sample_kagawa-d pull request #15
Opened 2021-02-07 12:48 UTC by mk299

# What
- マイページからクレジットカードの登録、削除
- payjpを利用した商品購入機能
- 購入された商品の状態を切り替える

# Why
フリマアプリにおいての購入機能は必須となるため。

2021-02-18 04:26 UTC, syuji-yamamoto reviewed
レビュー依頼ありがとうございます！
コードを確認させていただきました！
コメントしましたので、ご確認ください！

2021-02-18 04:26 UTC, syuji-yamamoto commented on app/controllers/credit_cards_controller.rb
> +    else
```
if @card.blank?
else
```
if文のあとの条件式がないので、少し冗長に見えます。
unlessなどで置き換えれないでしょうか？
例)
```
unless @card.blank?
  ~~~~~~
```
[参考リファレンス](https://docs.ruby-lang.org/ja/latest/doc/spec=2fcontrol.html)

2021-02-18 04:26 UTC, syuji-yamamoto commented on app/views/items/done.html.haml
> +-# = render "layouts/breadcrumb"
こちらの記述は使用していないのであれば可読性向上のため、コメントアウトは削除しておくと良いでしょう。
この実装の後にコメントアウトを外す予定であればそのままで大丈夫です。

2021-02-18 04:26 UTC, syuji-yamamoto commented on app/views/items/show.html.haml
> +              - if current_user.id == @item.user_id
```&&```などの論理演算子を使用すればもう少しコード量を減らせそうです。
参考例）
```
if 商品状態が0の時
  if ユーザーがログインしている かつ ログインしているユーザーのidと商品のユーザーidが一致する時
```
[参考リファレンス](https://docs.ruby-lang.org/ja/latest/doc/spec=2foperator.html)

2021-02-18 04:26 UTC, syuji-yamamoto commented on app/views/items/show.html.haml
> +              - else user_signed_in? && current_user.id
``` - else user_signed_in? && current_user.id```
条件式を記述するのであれば、```elsif```にしましょう。
```else```であれば条件式は不要です。

2021-02-18 05:31 UTC, mk299 commented on app/controllers/credit_cards_controller.rb
> +    else
if を unless に置き換えました。

2021-02-18 05:32 UTC, mk299 commented on app/views/items/done.html.haml
> +-# = render "layouts/breadcrumb"
パンくずリストの表示を追加しました。

2021-02-18 05:32 UTC, mk299 commented on app/views/items/show.html.haml
> +              - if current_user.id == @item.user_id
論理演算子を使って条件式をまとめました。

2021-02-18 05:33 UTC, mk299 commented on app/views/items/show.html.haml
> +              - else user_signed_in? && current_user.id
条件式が必要なので elsif に変更しました。

2021-02-18 06:03 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
修正点確認させていただきました。
追加でコメントいたしましたので、ご確認お願いします！

2021-02-18 06:03 UTC, yupimaru commented on app/controllers/items_controller.rb
> +      else
```ruby
      if @card.blank?
      else
```

上記ですが、ifの条件式がtrueのときの処理は有りませんか？
ないのであれば、`unless`でも良いかと思います。

2021-02-18 06:38 UTC, mk299 commented on app/assets/javascripts/modules/card_form.js
> +  var payjp = Payjp('pk_test_776d589fe4bc495507e8a5f0');
変数定義をconstに変更しました。

2021-02-18 06:40 UTC, mk299 commented on app/assets/javascripts/modules/card_form.js
> +        $('#expiry-form').removeAttr('name');
`$('#card_form')[0].submit();`
以外は不要なので削除しました。

2021-02-18 06:40 UTC, mk299 commented on app/controllers/credit_cards_controller.rb
> +    else
`unles`に変更しました。

2021-02-18 06:43 UTC, mk299 commented on app/controllers/credit_cards_controller.rb
> +      else
`unless`に変更しました。

2021-02-18 06:44 UTC, mk299 commented on app/controllers/items_controller.rb
> +      else
`unless`に変更しました。

2021-02-18 06:53 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
修正点確認させていただきました。
追加でコメントいたしましたので、ご確認お願いします！

2021-02-18 06:53 UTC, yupimaru commented on app/assets/javascripts/modules/card_form.js
> +        $('#card_form')[0].submit();
```ruby
$('#card_form')[0].submit();
```

上記記述だけで、不要なデータがサーバーへ送られないように制御できていますか？
（もし、問題ないのであればこのままで大丈夫です！）

2021-02-18 10:57 UTC, mk299 commented on app/assets/javascripts/modules/card_form.js
> +        $('#card_form')[0].submit();
問題ないようです。

2021-02-19 04:03 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
挙動確認いただきありがとうございました！！

問題なく動作するとのことですので、LGTMとさせていただきます！実装お疲れ様でした！
マージして本番環境にデプロイ後、確認をお願いします！
引き続き、最終課題の実装頑張っていきましょう！

2021-02-19 04:21 UTC, mk299 commented
ありがとうございました。

2021-02-19 04:24 UTC, merged