[WIP]商品詳細表示機能の実装
mk299/fleamarket_sample_kagawa-d pull request #16
Opened 2021-02-08 10:36 UTC by obami1105

# What
商品の詳細情報を確認することができるようにする

# Why
出品者による編集/削除、また出品者以外のユーザーが商品購入へ進むための窓口として必須となるため

2021-02-16 10:07 UTC, yupimaru requested changes
レビュー依頼ありがとうございます！
コメントしましたので、ご確認をお願いいたします！

2021-02-16 10:07 UTC, yupimaru commented on app/assets/stylesheets/modules/_items_show.scss
> +    color: #fff;
```SCSS
 #fff
```

繰り返し使用する色コードは変数化しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on config/routes.rb
> +    get 'item', to: 'items#show'
```ruby
get 'item', to: 'items#show'
```

上記ルーティングは不要であるように感じます！

2021-02-16 10:07 UTC, yupimaru commented on config/routes.rb
> +  get 'item', to: 'items#show'
```ruby
get 'item', to: 'items#show'
```

上記ルーティングは不要であるように感じます！

2021-02-16 10:07 UTC, yupimaru commented on spec/factories/conditions.rb
> +FactoryBot.define do
**spec/factories/conditions.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/factories/preparation_days.rb
> +FactoryBot.define do
**spec/factories/preparation_days.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/factories/shipping_fee_payers.rb
> +FactoryBot.define do
**spec/factories/shipping_fee_payers.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/models/category_spec.rb
> +require 'rails_helper'
**spec/models/category_spec.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/models/condition_spec.rb
> +require 'rails_helper'
**spec/models/condition_spec.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/models/preparation_day_spec.rb
> +require 'rails_helper'
**spec/models/preparation_day_spec.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:07 UTC, yupimaru commented on spec/models/shipping_fee_payer_spec.rb
> +require 'rails_helper'
**spec/models/shipping_fee_payer_spec.rb**

こちらのファイルですが、使用予定がなければファイルごと削除しておきましょう！

2021-02-16 10:33 UTC, obami1105 commented on config/routes.rb
> +    get 'item', to: 'items#show'
削除しました。

2021-02-16 10:34 UTC, obami1105 commented on config/routes.rb
> +  get 'item', to: 'items#show'
削除しました。

2021-02-16 10:40 UTC, obami1105 commented on spec/factories/conditions.rb
> +FactoryBot.define do
ファイルごと削除しました。

2021-02-16 10:41 UTC, obami1105 commented on spec/factories/preparation_days.rb
> +FactoryBot.define do
ファイルごと削除しました。

2021-02-16 10:51 UTC, obami1105 commented on spec/factories/shipping_fee_payers.rb
> +FactoryBot.define do
ファイルごと削除しました。

2021-02-16 10:53 UTC, obami1105 commented on spec/models/category_spec.rb
> +require 'rails_helper'
ファイルごと削除しました。

2021-02-16 10:53 UTC, obami1105 commented on spec/models/condition_spec.rb
> +require 'rails_helper'
ファイルごと削除しました。

2021-02-16 10:54 UTC, obami1105 commented on spec/models/preparation_day_spec.rb
> +require 'rails_helper'
ファイルごと削除しました。

2021-02-16 10:55 UTC, obami1105 commented on spec/models/shipping_fee_payer_spec.rb
> +require 'rails_helper'
ファイルごと削除しました。

2021-02-16 11:20 UTC, obami1105 commented on app/assets/stylesheets/modules/_items_show.scss
> +    color: #fff;
修正しました。

2021-02-17 04:00 UTC, yupimaru reviewed
レビュー依頼ありがとうございます！
修正点確認させて頂きました。

今回の修正をもって、**LGTM**とさせていただきます。
商品詳細機能の実装お疲れ様でした！

masterブランチへマージ後、次の実装へ進みましょう。
引き続き実装頑張っていきましょう。応援しております！

2021-02-17 04:12 UTC, obami1105 commented
ご確認並びにご指導頂き、ありがとうございました◎

2021-02-17 04:13 UTC, merged