【WIP】商品詳細ページの実装
mk299/fleamarket_sample_kagawa-d pull request #4
Opened 2021-01-17 03:09 UTC by sabaguchi

#What

#Why

2021-01-24 05:09 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。

また、修正後再度提出される際には、現在ブラウザ上でどのように表示されているのか確認させて頂きたい為、Gyazoを用いてスクリーンショットを撮影して頂き、生成されたURLを併せてご提出下さい。

2021-01-24 05:09 UTC, yupimaru commented on app/assets/stylesheets/modules/_items_show.scss
> +              color: #333;
```scss
#333
```

繰り返し使用する色は変数化して使用しましょう。

2021-01-24 05:09 UTC, yupimaru commented on app/views/items/show.html.haml
> +      %h.Item__Name ご飯
```haml
%h
```

`hタグ`を用いている理由は何でしょうか？？

2021-01-24 05:09 UTC, yupimaru commented on app/views/items/show.html.haml
> +          コメントする
```haml
      = form_with(url: "#", local: true, method: :post, class: "Form") do |f|
        %textarea.CommentText
        %p.NoticeMsg 
          相手のことを考え丁寧なコメントを心がけましょう。
          %br
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %br
        %button{type: "submit", class: "FormSendBtn"}
          = icon('fa', 'comment')
          コメントする
```

`form_with`を用いて記載するのであれば、入力欄や送信ボタンもform_withを用いることで使用できるhtmlタグを用いて記載しましょう。

2021-01-24 05:09 UTC, yupimaru commented on app/views/items/show.html.haml
> +          %a.Item__Wrapper(href="#")
```haml
%a.Item__Wrapper(href="#")
```

aタグは直接記載するのではなく、Railsのヘルパーメソッドを用いて記述しましょう。
他の箇所も同様です。

2021-01-24 05:09 UTC, yupimaru commented on config/routes.rb
> +  resources :items
```rb
resources :items
```

本当に現時点で7つのアクション全て必要でしょうか？
不要なルーティングを生成すると、予期せぬエラーを引き起こす原因ともなります。
必要なものを必要なタイミングで記載しましょう。

2021-01-24 05:09 UTC, yupimaru commented on app/assets/stylesheets/modules/_items_show.scss
> +}
```SCSS
                }
              }
            }
          }
        }
      }
    }
  }
} 
```

ネストが深すぎます。
SCSSのネストは3階層程度にしましょう。
階層が深くなると、コードの可読性低下やメンテンナンスに時間がかかるなどデメリットがあります。

2021-01-24 05:09 UTC, yupimaru commented on app/assets/stylesheets/modules/_items_show.scss
> +              }
```SCSS
               td{
                    width: 61%;
                  padding: 15px 15px;
                  border: 1px solid #dedede;
                  font-size: 14px;
              }
```

インデントを整えましょう。

2021-01-24 13:24 UTC, sabaguchi commented
以下の点、修正しました。
・scssで、繰り返し使用される色を変数化して使用。
・hタグをpタグに変更。（見出しにする必要がなかったため。）
・form_withの要素を変更。（submitについては、FontAwesomeアイコンとの共存のため、button_tagにより記載。）
・aタグを、ヘルパーメソッドにより記載。
・ルーティングを、indexとshowに限定。
・scssの階層を３層までに変更。
・インテンドの修正。

2021-01-24 13:42 UTC, sabaguchi commented
Gyazoでのページ全体のスクリーンショットへのリンクです。
ご確認をよろしくお願い致します。

https://gyazo.com/902b34e951ecd9c8993b36cf98fe5544

2021-01-26 04:00 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
修正点を確認させていただきました！
LGTMとさせていただきます！実装お疲れ様でした！
マージして本番環境にデプロイ後、確認をお願いします！
引き続き、最終課題の実装頑張っていきましょう！

2021-01-26 14:25 UTC, merged