[WIP]新規ユーザー登録・ログインページのマークアップ
mk299/fleamarket_sample_kagawa-d pull request #5
Opened 2021-01-17 03:22 UTC by omatsu0128

#What
新規ユーザー登録画面、ログイン画面を作る

#Why
トップページの次に使う画面のため

2021-01-18 22:13 UTC, omatsu0128 commented
主にview/devise/registrations/new.html.haml と、assets/stylesheets/_user.scss を編集しました。
pictweetを参考にしたため、scssに最初から記述がある状態で編集していきました。
hamlとscssの記述方法を忘れた状態で編集していったので、今日の夕方記述方法を教えていただきたいと思います。

2021-01-24 05:18 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
コメントしておりますので、ご確認のほどよろしくお願いいたします。
また、今回作業されているのは**マークアップ**かと思われます。
一部サーバーサイド実装と見受けられる箇所もございました。
混在させないように注意して下さい。

また、修正後再度提出される際には、実際にブラウザ上でどのように表示されているのか確認させて頂きたい為、Gyazoを用いてスクリーンショットを撮影して頂き、生成されるURLを併せてご提出下さい。

2021-01-24 05:18 UTC, yupimaru commented on app/assets/stylesheets/modules/_user_new_log_in.scss
> +        border: 1px solid #0099e8;
```SCSS
 #0099e8
```

繰り返し使用する色は、変数化して使用しましょう。

2021-01-24 05:18 UTC, yupimaru commented on app/controllers/application_controller.rb
> +  end
```rb
before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
end
```

マークアップの段階でこちらの記述は不要かと思われます。
削除しましょう。

2021-01-24 05:18 UTC, yupimaru commented on app/views/layouts/mailer.html.haml
> +!!!
**app/views/layouts/mailer.html.haml**

こちらのファイルは、今回のフリマアプリ開発では不要ですので、ファイルごと削除しておきましょう。

2021-01-24 05:18 UTC, yupimaru commented on app/views/layouts/mailer.text.haml
> += yield
**app/views/layouts/mailer.text.haml**

こちらのファイルは、今回のフリマアプリ開発では不要ですので、ファイルごと削除しておきましょう。

2021-01-24 05:18 UTC, yupimaru commented on config/routes.rb
> +  resources :users
```rb
resources :items
resources :users
```

本当に現時点でそれぞれ7つのアクションが必要ですか？
不要なルーティングを生成すると、予期せぬエラーの原因となります。
必要なタイミングで必要なルーティングを記述しましょう。
新規ユーザー登録・ログインページのマークアップにおいて、itemsやusersのパスは使用しないはずです。

2021-01-24 21:12 UTC, omatsu0128 commented
新規登録：https://gyazo.com/d6171e50cffb362dfebfcbe472f55a58
ログイン：https://gyazo.com/be22944307292676f32c6f2a2092452d

レビューありがとうございます。
修正①で、ご指摘いただいた箇所を修正しました。
修正②で、その他カラーで変数を使える部分を修正、不要な記述が見つかりましたので削除しました。

2021-01-26 04:00 UTC, syuji-yamamoto reviewed
レビュー依頼ありがとうございます！
修正点を確認させていただきました！
数点、追加でコメントしましたので、ご確認をお願いします！

2021-01-26 09:50 UTC, omatsu0128 commented
レビューありがとうございます。全て修正しました。
修正後の見た目は下記のリンクの通りとなります。
https://gyazo.com/dc4427f3c0c8ba7153e79e584b9c5ceb
https://gyazo.com/b1af7e416eeaf94cb7e66ea5e7b61684

2021-01-26 09:55 UTC, omatsu0128 commented on app/views/devise/sessions/new.html.haml
> +            = link_to 'パスワードをお忘れの方', "", class: 'pass_forget'
#を間に入れました。

2021-01-26 09:55 UTC, omatsu0128 commented on app/views/layouts/_footer_user.html.haml
> +    %a{href: "/"}
aタグをlink_toに変更し、image_tagを取り込みました。

2021-01-26 09:55 UTC, omatsu0128 commented on app/views/layouts/_header_user.html.haml
> +    %a{href: "/"}
aタグをlink_toに変更し、image_tagを取り込みました。

2021-01-26 10:00 UTC, syuji-yamamoto reviewed
レビュー依頼ありがとうございます！
修正点を確認させていただきました！
一点だけコメントしましたので、ご確認ください！

2021-01-26 10:00 UTC, syuji-yamamoto commented on app/views/devise/sessions/new.html.haml
> +        = link_to '新規会員登録', "/users/sign_up",class: "new_user_btn"
``` "/users/sign_up"```
パスはURLを直接書くのではなく、prefixを使用しましょう！
他の箇所も同様に見直しておきましょう。

2021-01-26 10:36 UTC, omatsu0128 commented on app/views/devise/sessions/new.html.haml
> +        = link_to '新規会員登録', "/users/sign_up",class: "new_user_btn"
prefix_pathへ変更しました。

2021-01-26 10:39 UTC, syuji-yamamoto commented
レビュー依頼ありがとうございます！
修正点を確認させていただきました！
LGTMとさせていただきます！実装お疲れ様でした！
マージして本番環境にデプロイ後、確認をお願いします！
引き続き、最終課題の実装頑張っていきましょう！

2021-01-26 10:48 UTC, merged