[WIP]マークアップ：商品出品ページ
mk299/fleamarket_sample_kagawa-d pull request #6
Opened 2021-01-17 04:41 UTC by obami1105

# What

# Why

2021-01-26 04:00 UTC, syuji-yamamoto reviewed
レビュー依頼ありがとうございます！
コメントしましたので、ご確認ください。

2021-01-26 17:07 UTC, obami1105 commented on app/views/items/new.html.haml
> +        %input.Form__inputPrice{"placeholder": 0, name: 'item[price]', id: 'item_price',"type": "number"}
修正しました。

2021-01-26 17:07 UTC, obami1105 commented on app/views/items/new.html.haml
> +        = link_to 'もどる', "/" , class: "Bach_btn"
修正しました。

2021-01-26 18:10 UTC, obami1105 commented on app/views/items/new.html.haml
> +        %textarea.Form__inputText__second{"rows":7, "placeholder": "商品の説明（必須1,000文字以内）
修正しました。

2021-01-26 18:11 UTC, obami1105 commented on app/views/items/new.html.haml
> +        %input.Form__inputText{"placeholder": "40文字まで", "type": "text"}
f.textfieldにて修正しました。

2021-01-27 00:31 UTC, obami1105 commented
修正後の画面のURLを添付いたします。

【商品出品ページ：スクリーンショット】
https://gyazo.com/91d4d2a42cc4eaf4e07557cdc1d0abc0

2021-01-27 04:01 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

追加でコメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-01-27 11:43 UTC, obami1105 commented
ご指摘いただきました箇所を修正いたしました。
改めて、ご確認の程お願いいたします。

修正後の画面のURLを添付いたします。
【商品出品ページ：スクリーンショット】
https://gyazo.com/319112816a70a6ff4994112cf4bc4a64

2021-01-28 05:59 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。

今回の修正をもって**LGTM**とさせて頂きます。
商品出品ページのマークアップお疲れさまでした。

masterブランチへマージ後、次の実装へ進みましょう。
引き続き、実装頑張っていきましょう。

2021-01-28 06:48 UTC, merged