【WIP】ユーザー機能の実装
mk299/fleamarket_sample_kagawa-d pull request #7
Opened 2021-01-20 11:13 UTC by mk299

# What
・device導入
・ユーザー新規登録
・ログイン、ログアウト　※ログインはメールアドレスのみ
・ログイン、ログアウト時にヘッダーが変わる

# Why
本アプリは登録したユーザーが出品・購入できるフリマサービスとなるので、ユーザー機能は必須。

2021-01-29 03:38 UTC, obami1105 commented
LGTMです◎

2021-01-30 03:08 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。

コメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-01-30 06:38 UTC, mk299 commented on app/controllers/users/confirmations_controller.rb
> +# frozen_string_literal: true
不要ファイルそ削除しました。

2021-01-30 06:38 UTC, mk299 commented on app/controllers/users/omniauth_callbacks_controller.rb
> +# frozen_string_literal: true
不要ファイルそ削除しました。

2021-01-30 06:38 UTC, mk299 commented on app/controllers/users/passwords_controller.rb
> +# frozen_string_literal: true
不要ファイルそ削除しました。

2021-01-30 06:38 UTC, mk299 commented on app/controllers/users/sessions_controller.rb
> +# frozen_string_literal: true
不要ファイルそ削除しました。

2021-01-30 06:38 UTC, mk299 commented on app/controllers/users/unlocks_controller.rb
> +# frozen_string_literal: true
不要ファイルそ削除しました。

2021-01-30 06:39 UTC, mk299 commented on app/models/user.rb
> +  validates :family_name, presence: true, format: { with: VALID_FAMILYNAME_REGEX }
重複記述を`VALID_NAME_REGEX`としてまとめました。

2021-01-30 06:40 UTC, mk299 commented on app/models/user.rb
> +  validates :family_name_kana, presence: true, format: { with: VALID_FAMILYNAMEKANA_REGEX }
重複記述を`VALID_KANA_REGEX`としてまとめました。

2021-01-30 06:45 UTC, mk299 commented on spec/factories/destinations.rb
> +    post_code      {"760-0023"}
DB設計に沿ってpost_codeカラムを**string型**に変更しましたので、該当箇所は{"760-0023"}のままにしてあります。
念のためpost_codeの型変更後にハイフン付きで保存されたことを確認しております。

2021-01-30 06:47 UTC, mk299 commented on spec/models/destination_spec.rb
> +      destination = build(:destination)
共通処理をbefore句で記述しました。

2021-01-30 06:47 UTC, mk299 commented on spec/models/user_spec.rb
> +      user = build(:user)
共通処理をbefore句で記述しました。

2021-01-30 06:48 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
emailに対するテストケースを追加しました。

2021-01-30 06:49 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
ユーザー本名入力に対するテストケースを追加しました。

2021-01-30 06:50 UTC, mk299 commented on spec/factories/destinations.rb
> +    prefecture_id  {"37"}
integer型に変更しました。

2021-01-30 06:52 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
パスワードが**7文字に満たないときに登録できないこと**を確認する記述に変更しました。

2021-01-30 06:53 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
`ユーザー本名は全角で入力`に対するテストケースを追加しました。

2021-01-30 07:40 UTC, yupimaru requested changes
レビュー依頼ありがとうございます。
修正点確認させて頂きました！

追加でコメントしておりますので、ご確認のほどよろしくお願いいたします。

2021-01-30 07:40 UTC, yupimaru commented on spec/models/user_spec.rb
> +    end
32行目から36行目の記述と、18行目から22行目の記述が重複しているように見受けられます。

2021-01-30 07:40 UTC, yupimaru commented on spec/models/user_spec.rb
> +    end
```ruby
    it 'emailは@とドメインがなければ登録できないこと' do
      @user.email = "aaa＠aaa,com"
      @user.valid?
      expect(@user.errors[:email]).to include("は不正な値です")
    end
```

上記のテストですが、以下の2つに切り分けましょう。
テストで確認することは1つにしておいたほうが、整合性が高いと言えるでしょう。
```
- emailに@が含まれていない場合、登録できないこと
- emailにドメインが含まれていない場合、登録できないこと
```

2021-01-30 07:54 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
重複箇所を削除しました。

2021-01-30 07:55 UTC, mk299 commented on spec/models/user_spec.rb
> +    end
emailのテストケースを@とドメインに分けました。

2021-01-30 08:24 UTC, yupimaru reviewed
レビュー依頼ありがとうございます。
修正点確認させて頂きました。とてもきれいなコードになりましたね！

1点のみコメントしておりますが、こちらを修正頂きましたら**LGTM**とさせて頂きます。
ご自身で修正頂きましたら、再レビューの必要はございません。
ユーザー機能の実装お疲れ様でした。

masterブランチへマージして頂き、次の実装へ進みましょう。
引き続き、実装頑張っていきましょう。応援しております。

2021-01-30 08:24 UTC, yupimaru commented on spec/models/user_spec.rb
> +      @user.email = "aaa＠aaa.com"
```ruby
@user.email = "aaa＠aaa.com"
```

it文が、`emailに@が含まれていない場合登録できないこと`とありますので、
実際にテストするメールアドレスも`@`がない状態にしておくのがふさわしいです。
以下の通り、修正しておきましょう。

```ruby
@user.email = "aaaaaa.com"
```

2021-01-30 08:29 UTC, mk299 commented on spec/models/user_spec.rb
> +      @user.email = "aaa＠aaa.com"
修正いたしました。
ありがとうございました。

2021-01-30 08:31 UTC, merged